import { Router } from 'express';
import { requireAuth, AuthenticatedRequest } from '../jwt.js';
import { requireActiveOrTrial, checkAndIncrementUsage } from '../fairUse.js';

const router = Router();

router.post('/api/alt-text/demo', requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    await requireActiveOrTrial(req.user!.sub);
    await checkAndIncrementUsage(req.user!.sub);
    res.json({
      alt: 'Example alt text generated by Alt Text Pro.',
      timestamp: new Date().toISOString(),
    });
  } catch (err) {
    res.status(402).json({ error: (err as Error).message });
  }
});

export const altTextDemoRouter = router;
